### ISSUE TITLE
Resource Maps don't work

### ISSUE THREAD

**Issue by paugnu** [Codilar/magento2-banner-slider#1]
Hi,
It seems that  the resource maps don't work. I've checked the code and found the issue. In addition, it also seems that the remove option doesn't work properly (but this is related to the slick slider itself).
I'm going to create a pull request with the fixes that worked for me.

**Comment by jayankaghosh** [comment]
Hi @paugnu Is it working for you now? If yes then I'll happily merge the PR after taking a look at the code :)

**Comment by paugnu** [comment]
Hi @jayankaghosh, sorry for the late response.
Actually, I had many issues with the cache. It worked more or less fine so far, but I need to do other tests.

I'll close this issue and open a new one with many changes I've done so far.
