### ISSUE TITLE
Empty CMS Pages cache when saving slider

### ISSUE THREAD

**Issue by paugnu** [Codilar/magento2-banner-slider#3]
When we save the slider, it would be nice to empty the cache of all the pages which actually are using that slider id.
I'll send a pull request as well :)

**Comment by jayankaghosh** [comment]
That's a great idea. We initially didn't do it because we made the slider to be used as a part of a bigger tool, using Magento as only a backend system. I'll have a look at the PR and merge if everything seems okay. Let me know if you need anything from my side

**Comment by paugnu** [comment]
Hi :) I'll close this ticket and open a new one with many changes I've done so far.
